# config/evaluation.yaml
models:
  sd35_controlnet:
    base_path: "/home/ubuntu/models/stabilityai/stable-diffusion-3-medium-diffusers"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/controlnet-sd3.5"
    model_type: "sd3"
    model_class: "sd"
    num_inference_steps: 28
  sd21_controlnet:
    base_path: "stabilityai/stable-diffusion-2-1-base"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/sd21_controlnet/controlnet"
    model_type: "sd2"
    model_class: "sd"
    num_inference_steps: 50
  ldm_model_512:
    model_type: "ldm"
    model_class: "ldm"
    config_path: "/home/ubuntu/models/trained-diffusion/ldm/config-512-with-vq-f4.yaml"
    ckpt_path: "/home/ubuntu/models/trained-diffusion/ldm/ldm-seg-512-000074.ckpt"
    num_inference_steps: 200

inference:
  batch_size: 4
  num_inference_steps: 28
  resolution: 512
  seed: 23

# Multi-dataset configuration
datasets:
  drsk:
    name: "drsk-1k-seed-23"
    path: "~/datasets/drsk"
    num_samples: 1000
    seed: 23
    # Dataset-specific downstream task settings
    downstream_tasks:
      classification:
        num_classes: 3
        class_names: ["Inflammatory/Reactive", "Carcinoma", "Normal"]
        labeling_strategy: "multiclass_dominant"
      segmentation:
        num_classes: 5
        class_names: ["Unknown", "Background/Artifact", "Inflammatory/Reactive", "Carcinoma", "Normal"]
  
  bcss:
    name: "bcss-1k-seed-23"
    path: "~/datasets/bcss"
    num_samples: 1000
    seed: 23
    downstream_tasks:
      classification:
        num_classes: 4
        class_names: ["Invasive", "In-situ", "Benign", "Normal"]
        labeling_strategy: "multiclass_dominant"
      segmentation:
        num_classes: 5
        class_names: ["Outside ROI", "Invasive", "In-situ", "Benign", "Normal"]

  segpath:
    name: "segpath-1k-seed-23"
    path: "~/datasets/segpath"
    num_samples: 1000
    seed: 23
    downstream_tasks:
      classification:
        num_classes: 2
        class_names: ["Benign", "Malignant"]
        labeling_strategy: "binary_carcinoma"
        carcinoma_threshold: 0.1
      segmentation:
        num_classes: 3
        class_names: ["Background", "Benign", "Malignant"]

# Global dataset preparation parameters (can be overridden per dataset)
dataset_preparation:
  num_samples: 1000
  seed: 23

# Target datasets to process (comment/uncomment as needed)
target_datasets:
  - drsk
  - bcss
  - segpath

# Accelerate config
accelerate_config: "config/accelerate_config.yaml"

# Global downstream task settings (can be overridden per dataset)
downstream_tasks:
  enabled: true
  classification:
    enabled: true
    model: "resnet18"
    num_epochs: 20
    batch_size: 16
    learning_rate: 0.001
  segmentation:
    enabled: true
    model: "deeplabv3plus"
    encoder: "se_resnext101_32x4d"
    num_epochs: 30
    batch_size: 16
    learning_rate: 0.0005

# Conda environments
conda_envs:
  default: "envs/default.yaml"
  ldm: "envs/ldm.yaml"
  downstream: "envs/downstream.yaml"