# config/evaluation.yaml
models:
  sd35_controlnet:
    base_path: "/home/ubuntu/models/stabilityai/stable-diffusion-3-medium-diffusers"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/controlnet-sd3.5-segpath"
    model_type: "sd3"  # Specific model architecture
    model_class: "sd"  # Indicates which inference pipeline to use
    num_inference_steps: 28  # SD3-specific inference steps

inference:
  batch_size: 4
  num_inference_steps: 28 # Global default (fallback if not specified in model)
  resolution: 512
  seed: 23

# Dataset information
dataset_name: &dataset_name "segpath-1k-seed-23"
dataset: *dataset_name  # Using the alias to reference the anchor

# Data source information
data_sources:
  *dataset_name:
    path: "~/datasets/segpath/data/val"

# Dataset preparation parameters
dataset_preparation:
  num_samples: 1000
  seed: 23

# Accelerate config
accelerate_config: "config/accelerate_config.yaml"

# --- Conda Environments ---
conda_envs:
  default: "envs/default.yaml" # Assumes env with torch, torchvision, torchmetrics, pyyaml, etc.
  ldm: "envs/ldm.yaml"
  downstream: "envs/downstream.yaml" # New environment for downstream tasks