# config/evaluation.yaml

# Define dataset keys as anchors
dataset_keys:
  drsk: &drsk_key "drsk-1k-seed-23"
  bcss: &bcss_key "bcss-1k-seed-23"
  segpath: &segpath_key "segpath-1k-seed-23"

# Define datasets - single source of truth
datasets:
  *drsk_key:
    path: "~/datasets/drsk"
    num_samples: 1000
    seed: 23
  *bcss_key:
    path: "~/datasets/bcss"
    num_samples: 1000
    seed: 23
  *segpath_key:
    path: "~/datasets/segpath"
    num_samples: 1000
    seed: 23

# Define models with dataset key references
models:
  sd35_controlnet_bcss:
    base_path: "/home/ubuntu/models/stabilityai/stable-diffusion-3-medium-diffusers"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/controlnet-sd3.5-bcss"
    model_type: "sd3"
    model_class: "sd"
    num_inference_steps: 28
    dataset_key: *bcss_key  # Reference using anchor
    
  sd35_controlnet_drsk:
    base_path: "/home/ubuntu/models/stabilityai/stable-diffusion-3-medium-diffusers"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/controlnet-sd3.5-drsk"
    model_type: "sd3"
    model_class: "sd"
    num_inference_steps: 28
    dataset_key: *drsk_key  # Reference using anchor
    
  sd35_controlnet_segpath:
    base_path: "/home/ubuntu/models/stabilityai/stable-diffusion-3-medium-diffusers"
    controlnet_path: "/home/ubuntu/models/trained-diffusion/controlnet-sd3.5-segpath"
    model_type: "sd3"
    model_class: "sd"
    num_inference_steps: 50
    dataset_key: *segpath_key  # Reference using anchor
    
  sd21_controlnet:
    base_path: "stabilityai/stable-diffusion-2-1-base"  # Can be HF ID or local path
    controlnet_path: "/home/ubuntu/models/trained-diffusion/sd21_controlnet/controlnet"
    model_type: "sd2"  # Specific model architecture
    model_class: "sd"  # Indicates which inference pipeline to use
    num_inference_steps: 50  # SD2-specific inference steps
  ldm_model_512:
    model_type: "ldm"  # Specific model architecture
    model_class: "ldm"  # Indicates which inference pipeline to use
    config_path: "/home/ubuntu/models/trained-diffusion/ldm/config-512-with-vq-f4.yaml"
    ckpt_path: "/home/ubuntu/models/trained-diffusion/ldm/ldm-seg-512-000074.ckpt"
    num_inference_steps: 200  # LDM-specific inference steps

# Rest of config remains the same...
inference:
  batch_size: 4
  num_inference_steps: 28
  resolution: 512
  seed: 23

dataset_preparation:
  num_samples: 1000
  seed: 23

accelerate_config: "config/accelerate_config.yaml"

downstream_tasks:
  enabled: true
  classification:
    enabled: true
    model: "resnet18"
    num_epochs: 20
    batch_size: 16
    learning_rate: 0.001
    labeling_strategy: "multiclass_dominant"
    carcinoma_threshold: 0.1
    num_classes: 3
    class_names: ["Inflammatory/Reactive", "Carcinoma", "Normal"]
  segmentation:
    enabled: true
    model: "deeplabv3plus"
    encoder: "se_resnext101_32x4d"
    num_epochs: 30
    batch_size: 16
    learning_rate: 0.0005
    num_classes: 5
    class_names: ["Unknown", "Background/Artifact", "Inflammatory/Reactive", "Carcinoma", "Normal"]

conda_envs:
  default: "envs/default.yaml"
  ldm: "envs/ldm.yaml"
  downstream: "envs/downstream.yaml"